// Quran Data
const quranData = {
    surahs: [
        { number: 1, name: "الفاتحه", translation: "گشاینده", type: "مکی", verses: 7, juz: 1 },
        { number: 2, name: "البقره", translation: "گاو", type: "مدنی", verses: 286, juz: 1 },
        { number: 3, name: "آل‌عمران", translation: "خاندان عمران", type: "مدنی", verses: 200, juz: 3 },
        { number: 4, name: "النساء", translation: "زنان", type: "مدنی", verses: 176, juz: 4 },
        { number: 5, name: "المائده", translation: "سفره", type: "مدنی", verses: 120, juz: 6 },
        { number: 6, name: "الأنعام", translation: "چارپایان", type: "مکی", verses: 165, juz: 7 },
        { number: 7, name: "الأعراف", translation: "اعراف", type: "مکی", verses: 206, juz: 8 },
        { number: 8, name: "الأنفال", translation: "غنائم جنگی", type: "مدنی", verses: 75, juz: 9 },
        { number: 9, name: "التوبه", translation: "توبه", type: "مدنی", verses: 129, juz: 10 },
        { number: 10, name: "یونس", translation: "یونس", type: "مکی", verses: 109, juz: 11 },
        { number: 11, name: "هود", translation: "هود", type: "مکی", verses: 123, juz: 11 },
        { number: 12, name: "یوسف", translation: "یوسف", type: "مکی", verses: 111, juz: 12 },
        { number: 13, name: "الرعد", translation: "رعد", type: "مدنی", verses: 43, juz: 13 },
        { number: 14, name: "ابراهیم", translation: "ابراهیم", type: "مکی", verses: 52, juz: 13 },
        { number: 15, name: "الحجر", translation: "حجر", type: "مکی", verses: 99, juz: 14 },
        { number: 16, name: "النحل", translation: "زنبور عسل", type: "مکی", verses: 128, juz: 14 },
        { number: 17, name: "الإسراء", translation: "شب‌گردی", type: "مکی", verses: 111, juz: 15 },
        { number: 18, name: "الکهف", translation: "غار", type: "مکی", verses: 110, juz: 15 },
        { number: 19, name: "مریم", translation: "مریم", type: "مکی", verses: 98, juz: 16 },
        { number: 20, name: "طه", translation: "طه", type: "مکی", verses: 135, juz: 16 },
        { number: 21, name: "الأنبیاء", translation: "پیامبران", type: "مکی", verses: 112, juz: 17 },
        { number: 22, name: "الحج", translation: "حج", type: "مدنی", verses: 78, juz: 17 },
        { number: 23, name: "المؤمنون", translation: "مؤمنان", type: "مکی", verses: 118, juz: 18 },
        { number: 24, name: "النور", translation: "نور", type: "مدنی", verses: 64, juz: 18 },
        { number: 25, name: "الفرقان", translation: "فرقان", type: "مکی", verses: 77, juz: 18 },
        { number: 26, name: "الشعراء", translation: "شعرا", type: "مکی", verses: 227, juz: 19 },
        { number: 27, name: "النمل", translation: "مورچگان", type: "مکی", verses: 93, juz: 19 },
        { number: 28, name: "القصص", translation: "داستان‌ها", type: "مکی", verses: 88, juz: 20 },
        { number: 29, name: "العنکبوت", translation: "عنکبوت", type: "مکی", verses: 69, juz: 20 },
        { number: 30, name: "الروم", translation: "روم", type: "مکی", verses: 60, juz: 21 },
        { number: 31, name: "لقمان", translation: "لقمان", type: "مکی", verses: 34, juz: 21 },
        { number: 32, name: "السجده", translation: "سجده", type: "مکی", verses: 30, juz: 21 },
        { number: 33, name: "الأحزاب", translation: "احزاب", type: "مدنی", verses: 73, juz: 21 },
        { number: 34, name: "سبأ", translation: "سبا", type: "مکی", verses: 54, juz: 22 },
        { number: 35, name: "فاطر", translation: "فاطر", type: "مکی", verses: 45, juz: 22 },
        { number: 36, name: "یس", translation: "یس", type: "مکی", verses: 83, juz: 22 },
        { number: 37, name: "الصافات", translation: "صافات", type: "مکی", verses: 182, juz: 23 },
        { number: 38, name: "ص", translation: "ص", type: "مکی", verses: 88, juz: 23 },
        { number: 39, name: "الزمر", translation: "زمر", type: "مکی", verses: 75, juz: 23 },
        { number: 40, name: "غافر", translation: "غافر", type: "مکی", verses: 85, juz: 24 },
        { number: 41, name: "فصلت", translation: "فصلت", type: "مکی", verses: 54, juz: 24 },
        { number: 42, name: "الشوری", translation: "شورا", type: "مکی", verses: 53, juz: 25 },
        { number: 43, name: "الزخرف", translation: "زخرف", type: "مکی", verses: 89, juz: 25 },
        { number: 44, name: "الدخان", translation: "دود", type: "مکی", verses: 59, juz: 25 },
        { number: 45, name: "الجاثیه", translation: "زانو زده", type: "مکی", verses: 37, juz: 25 },
        { number: 46, name: "الأحقاف", translation: "احقاف", type: "مکی", verses: 35, juz: 26 },
        { number: 47, name: "محمد", translation: "محمد", type: "مدنی", verses: 38, juz: 26 },
        { number: 48, name: "الفتح", translation: "پیروزی", type: "مدنی", verses: 29, juz: 26 },
        { number: 49, name: "الحجرات", translation: "حجرات", type: "مدنی", verses: 18, juz: 26 },
        { number: 50, name: "ق", translation: "ق", type: "مکی", verses: 45, juz: 26 },
        { number: 51, name: "الذاریات", translation: "بادهای پراکننده", type: "مکی", verses: 60, juz: 26 },
        { number: 52, name: "الطور", translation: "طور", type: "مکی", verses: 49, juz: 27 },
        { number: 53, name: "النجم", translation: "ستاره", type: "مکی", verses: 62, juz: 27 },
        { number: 54, name: "القمر", translation: "ماه", type: "مکی", verses: 55, juz: 27 },
        { number: 55, name: "الرحمن", translation: "رحمان", type: "مدنی", verses: 78, juz: 27 },
        { number: 56, name: "الواقعه", translation: "واقعه", type: "مکی", verses: 96, juz: 27 },
        { number: 57, name: "الحدید", translation: "آهن", type: "مدنی", verses: 29, juz: 27 },
        { number: 58, name: "المجادله", translation: "مجادله کننده", type: "مدنی", verses: 22, juz: 28 },
        { number: 59, name: "الحشر", translation: "حشر", type: "مدنی", verses: 24, juz: 28 },
        { number: 60, name: "الممتحنه", translation: "زن آزموده شده", type: "مدنی", verses: 13, juz: 28 },
        { number: 61, name: "الصف", translation: "صف", type: "مدنی", verses: 14, juz: 28 },
        { number: 62, name: "الجمعه", translation: "جمعه", type: "مدنی", verses: 11, juz: 28 },
        { number: 63, name: "المنافقون", translation: "منافقان", type: "مدنی", verses: 11, juz: 28 },
        { number: 64, name: "التغابن", translation: "تغابن", type: "مدنی", verses: 18, juz: 28 },
        { number: 65, name: "الطلاق", translation: "طلاق", type: "مدنی", verses: 12, juz: 28 },
        { number: 66, name: "التحریم", translation: "تحریم", type: "مدنی", verses: 12, juz: 28 },
        { number: 67, name: "الملک", translation: "ملک", type: "مکی", verses: 30, juz: 29 },
        { number: 68, name: "القلم", translation: "قلم", type: "مکی", verses: 52, juz: 29 },
        { number: 69, name: "الحاقه", translation: "حاقه", type: "مکی", verses: 52, juz: 29 },
        { number: 70, name: "المعارج", translation: "معارج", type: "مکی", verses: 44, juz: 29 },
        { number: 71, name: "نوح", translation: "نوح", type: "مکی", verses: 28, juz: 29 },
        { number: 72, name: "الجن", translation: "جن", type: "مکی", verses: 28, juz: 29 },
        { number: 73, name: "المزمل", translation: "جامه به خود پیچیده", type: "مکی", verses: 20, juz: 29 },
        { number: 74, name: "المدثر", translation: "جامه به خود پیچیده", type: "مکی", verses: 56, juz: 29 },
        { number: 75, name: "القیامه", translation: "قیامت", type: "مکی", verses: 40, juz: 29 },
        { number: 76, name: "الإنسان", translation: "انسان", type: "مدنی", verses: 31, juz: 29 },
        { number: 77, name: "المرسلات", translation: "فرستاده شدگان", type: "مکی", verses: 50, juz: 29 },
        { number: 78, name: "النبأ", translation: "خبر بزرگ", type: "مکی", verses: 40, juz: 30 },
        { number: 79, name: "النازعات", translation: "کندگان", type: "مکی", verses: 46, juz: 30 },
        { number: 80, name: "عبس", translation: "عبوس کرد", type: "مکی", verses: 42, juz: 30 },
        { number: 81, name: "التکویر", translation: "پیچیده شدن", type: "مکی", verses: 29, juz: 30 },
        { number: 82, name: "الإنفطار", translation: "شکافتن", type: "مکی", verses: 19, juz: 30 },
        { number: 83, name: "المطففین", translation: "کم فروشان", type: "مکی", verses: 36, juz: 30 },
        { number: 84, name: "الإنشقاق", translation: "شکافتن", type: "مکی", verses: 25, juz: 30 },
        { number: 85, name: "البروج", translation: "برج‌ها", type: "مکی", verses: 22, juz: 30 },
        { number: 86, name: "الطارق", translation: "ستاره", type: "مکی", verses: 17, juz: 30 },
        { number: 87, name: "الأعلی", translation: "والا", type: "مکی", verses: 19, juz: 30 },
        { number: 88, name: "الغاشیه", translation: "حادثه", type: "مکی", verses: 26, juz: 30 },
        { number: 89, name: "الفجر", translation: "فجر", type: "مکی", verses: 30, juz: 30 },
        { number: 90, name: "البلد", translation: "شهر", type: "مکی", verses: 20, juz: 30 },
        { number: 91, name: "الشمس", translation: "خورشید", type: "مکی", verses: 15, juz: 30 },
        { number: 92, name: "اللیل", translation: "شب", type: "مکی", verses: 21, juz: 30 },
        { number: 93, name: "الضحی", translation: "چاشتگاه", type: "مکی", verses: 11, juz: 30 },
        { number: 94, name: "الشرح", translation: "گشایش", type: "مکی", verses: 8, juz: 30 },
        { number: 95, name: "التین", translation: "انجیر", type: "مکی", verses: 8, juz: 30 },
        { number: 96, name: "العلق", translation: "خون بسته", type: "مکی", verses: 19, juz: 30 },
        { number: 97, name: "القدر", translation: "قدر", type: "مکی", verses: 5, juz: 30 },
        { number: 98, name: "البینه", translation: "بینه", type: "مدنی", verses: 8, juz: 30 },
        { number: 99, name: "الزلزله", translation: "زلزله", type: "مدنی", verses: 8, juz: 30 },
        { number: 100, name: "العادیات", translation: "تاختن", type: "مکی", verses: 11, juz: 30 },
        { number: 101, name: "القارعه", translation: "قارعه", type: "مکی", verses: 11, juz: 30 },
        { number: 102, name: "التکاثر", translation: "زیادتی", type: "مکی", verses: 8, juz: 30 },
        { number: 103, name: "العصر", translation: "عصر", type: "مکی", verses: 3, juz: 30 },
        { number: 104, name: "الهمزه", translation: "همزه", type: "مکی", verses: 9, juz: 30 },
        { number: 105, name: "الفیل", translation: "فیل", type: "مکی", verses: 5, juz: 30 },
        { number: 106, name: "قریش", translation: "قریش", type: "مکی", verses: 4, juz: 30 },
        { number: 107, name: "الماعون", translation: "ماعون", type: "مکی", verses: 7, juz: 30 },
        { number: 108, name: "الکوثر", translation: "کوثر", type: "مکی", verses: 3, juz: 30 },
        { number: 109, name: "الکافرون", translation: "کافران", type: "مکی", verses: 6, juz: 30 },
        { number: 110, name: "النصر", translation: "یاری", type: "مدنی", verses: 3, juz: 30 },
        { number: 111, name: "المسد", translation: "ریسمان", type: "مکی", verses: 5, juz: 30 },
        { number: 112, name: "الإخلاص", translation: "اخلاص", type: "مکی", verses: 4, juz: 30 },
        { number: 113, name: "الفلق", translation: "سپیده‌دم", type: "مکی", verses: 5, juz: 30 },
        { number: 114, name: "الناس", translation: "مردم", type: "مکی", verses: 6, juz: 30 }
    ]
};

// Sample Ayat (Limited for demonstration)
const sampleAyat = {
    1: [
        {
            number: 1,
            text: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            translation: "به نام خداوند بخشنده مهربان"
        },
        {
            number: 2,
            text: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
            translation: "ستایش مخصوص خداوندی است که پروردگار جهانیان است"
        },
        {
            number: 3,
            text: "الرَّحْمَٰنِ الرَّحِيمِ",
            translation: "بخشنده مهربان"
        },
        {
            number: 4,
            text: "مَالِكِ يَوْمِ الدِّينِ",
            translation: "فرمانروای روز جزا"
        },
        {
            number: 5,
            text: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
            translation: "تنها تو را می‌پرستیم و تنها از تو یاری می‌جوییم"
        },
        {
            number: 6,
            text: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
            translation: "ما را به راه راست هدایت کن"
        },
        {
            number: 7,
            text: "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
            translation: "راه کسانی که بر آنان نعمت دادی، نه کسانی که مورد غضب قرار گرفتند و نه گمراهان"
        }
    ]
};
